CREATE DATABASE Farmacia2;
USE Farmacia2

CREATE TABLE CLIENTES_frecuentes (
    ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_CLIENTE VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15) NULL,
    DIRECCION VARCHAR(100) NULL,
    FECHA_REGISTRO DATE NOT NULL DEFAULT GETDATE()
);
CREATE TABLE CLIENTES_0Registros (
      ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
);
CREATE TABLE Gerente (
    ID_Gerente INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_Gerente VARCHAR(50) NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15) NULL,
    FECHA_REGISTRO DATE NOT NULL DEFAULT GETDATE()


);
CREATE TABLE PAGOS_VENTAS (
    ID_PAGO_VENTA INT PRIMARY KEY IDENTITY(1,1),
    ID_COMPRA_CAJA INT NOT NULL, -- Hace referencia a CAJA
    MONTO DECIMAL(10,2) NOT NULL,
    FECHA_PAGO DATETIME NOT NULL DEFAULT GETDATE(),
    TIPO_PAGO VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID_COMPRA_CAJA) REFERENCES CAJA(ID_COMPRA)
);


CREATE TABLE PAGOS_SUPLIDORES (
    ID_PAGO_SUPLIDOR INT PRIMARY KEY IDENTITY(1,1),
    ID_COMPRA_SUPLIDOR INT NOT NULL, -- Hace referencia a COMPRAS_SUPLIDORES
    MONTO DECIMAL(10,2) NOT NULL,
    FECHA_PAGO DATETIME NOT NULL DEFAULT GETDATE(),
    TIPO_PAGO VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID_COMPRA_SUPLIDOR) REFERENCES COMPRAS_SUPLIDORES(ID_COMPRA)
);
CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_EMPLEADO VARCHAR(50) NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15) NULL,
    FECHA_REGISTRO DATE NOT NULL DEFAULT GETDATE()
);

CREATE TABLE CAJA (
    ID_COMPRA INT PRIMARY KEY IDENTITY(1,1),
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2),
    FECHA_COMPRA DATE NOT NULL DEFAULT GETDATE(),
    ID_EMPLEADO INT NOT NULL,

    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);
CREATE TABLE Pagos_caja (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Id_CompraP INT NOT NULL,                          -- Compra relacionada
    Monto DECIMAL(10,2) NOT NULL,                    -- Monto pagado
    FechaPago DATETIME NOT NULL DEFAULT GETDATE(),   -- Fecha y hora del pago
    Tipo_Pago VARCHAR(20) NOT NULL,                  -- Efectivo, Transferencia, etc.
    FOREIGN KEY (Id_CompraP) REFERENCES COMPRAS_SUPLIDORES(ID_COMPRA)
	);
	CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    STOCK INT NOT NULL,
    FECHA_REGISTRO DATE NOT NULL DEFAULT GETDATE(),
    FECHA_VENCIMIENTO DATE NOT NULL DEFAULT GETDATE(),
	UNIDAD_MEDIDA VARCHAR(10),
    PRECIO_MAYOR DECIMAL(10,2),
    PRECIO_DETALLE DECIMAL(10,2)
	);
CREATE TABLE Pagos (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Id_Compra INT NOT NULL,                          -- Compra relacionada
    Monto DECIMAL(10,2) NOT NULL,                    -- Monto pagado
    FechaPago DATETIME NOT NULL DEFAULT GETDATE(),   -- Fecha y hora del pago
    Tipo_Pago VARCHAR(20) NOT NULL,                  -- Efectivo, Transferencia, etc.
    FOREIGN KEY (Id_Compra) REFERENCES COMPRAS_SUPLIDORES(ID_COMPRA)
	);
ALTER TABLE pagos
DROP table pagos


CREATE TABLE SUPLIDORES (
    ID_EMPRESAS INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_EMPRESAS VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(15) NULL,
    FECHA_REGISTRO DATE NOT NULL DEFAULT GETDATE()
	
);
CREATE TABLE COMPRAS_SUPLIDORES (
    ID_COMPRA INT PRIMARY KEY IDENTITY(1,1),
    ID_EMPRESA INT NOT NULL,          -- Suplidor
    ID_PRODUCTO INT NOT NULL,          -- Producto comprado
    CANTIDAD INT NOT NULL,             -- Cuántas unidades se compraron
    PRECIO_UNITARIO DECIMAL(10,2),     -- Precio por unidad en esta compra
    FECHA_COMPRA DATE NOT NULL DEFAULT GETDATE(),
    -- Claves foráneas
        FOREIGN KEY (ID_EMPRESA) REFERENCES SUPLIDORES(ID_EMPRESAS),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

	--gerente