using System;
using System.Windows.Forms;
using System.Data.SqlClient; // Added for explicit SQL error handling

namespace Inventario_de_farmacia
{
    public partial class Productos : Form
    {
        public Productos()
        {
            InitializeComponent();
        }

        private void Productos_Load(object sender, EventArgs e)
        {
            // TODO: esta línea de código carga datos en la tabla 'fARMACIA1DataSet1.PRODUCTOS' Puede moverla o quitarla según sea necesario.
            this.pRODUCTOSTableAdapter1.Fill(this.fARMACIA1DataSet1.PRODUCTOS);
            // The "TODO" comment indicates this code was likely generated by Visual Studio.
            // We'll replace it with a more robust way to load data and ensure it uses FARMACIA1DataSet.

            try
            {
                // Fill the PRODUCTOS table adapter using the FARMACIA1DataSet.
                // This assumes your Productos.Designer.cs has been updated
                // to use FARMACIA1DataSet and its corresponding TableAdapter.
                this.pRODUCTOSTableAdapter.Fill(this.fARMACIA1DataSet.PRODUCTOS);
            }
            catch (SqlException ex)
            {
                // Catch specific SQL exceptions for database-related errors
                MessageBox.Show($"Error de base de datos al cargar productos: {ex.Message}", "Error de Carga", MessageBoxButtons.OK, MessageBoxIcon.Error);
                // Optionally, log the exception details for debugging
            }
            catch (Exception ex)
            {
                // Catch any other unexpected errors
                MessageBox.Show($"Ocurrió un error inesperado al cargar productos: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                // Optionally, log the exception details for debugging
            }

            // The FormClosing event should ideally be hooked up in the designer or at initialization,
            // but it's okay here if you prefer to do it programmatically.
            // Just ensure it's not hooked up multiple times if this method can be called more than once.
            // If already set in Designer.cs, remove this line to avoid duplicate event subscriptions.
            // this.FormClosing += new FormClosingEventHandler(Cerrar); // Consider if this is needed if already in Designer.cs

            // Setting Visible to false immediately after load might hide the form unexpectedly.
            // This is usually done by a parent form when showing/hiding child forms.
            // If your intention is to hide it after initial load and show it later, this is fine.
            // If it's the main form, it might just flash and disappear.
            // this.Visible = false; // Review if this line is truly intended to hide the form on load.

            this.StartPosition = FormStartPosition.CenterScreen; // This is a good setting for form positioning.
        }

        private void Cerrar(object sender, FormClosingEventArgs e)
        {
            // Prevents the form from closing completely (e.Cancel = true).
            // Instead, it just hides the form (this.Visible = false).
            // This is useful if you want to reuse the form instance rather than creating a new one.
            e.Cancel = true;
            this.Visible = false;

            // Optional: If you have a main form or a specific form you want to show when this one is hidden,
            // you might add code here to show that other form.
            // Example:
            // if (Application.OpenForms["MainForm"] is MainForm mainForm)
            // {
            //     mainForm.Show();
            // }
        }
    }
}